ALTER TABLE servicios ADD COLUMN IF NOT EXISTS tipo_servicio VARCHAR(40) NOT NULL DEFAULT 'aseo';
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS tipo_plaga VARCHAR(40);
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS horas_incluidas INTEGER;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS iva INTEGER DEFAULT 0;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS retencion_honorarios INTEGER DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS push_token TEXT;

CREATE TABLE IF NOT EXISTS notificaciones (
	id SERIAL PRIMARY KEY,
	usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
	tipo VARCHAR(80) NOT NULL,
	titulo TEXT NOT NULL,
	mensaje TEXT NOT NULL,
	leida BOOLEAN NOT NULL DEFAULT FALSE,
	creado_en TIMESTAMP NOT NULL DEFAULT NOW()
);
